server:
  port: 8080
  connection-timeout: 30000
  tomcat:
    accept-count: 100 #default 达到最大连接数后的排队请求数量
    max-connections: 10000 #default 最大连接数
    max-threads: 200 #default 最大线程
    min-spare-threads: 10 #default 空闲线程
    uri-encoding: UTF-8
logging:
  config: classpath:log4j2.yml
  
spring:
  profiles:
    active: dev
  application:
    name: zcms
    
  thymeleaf:
    cache: false
    encoding: UTF-8
    
#  mvc:
#    static-path-pattern: /static/**
  


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/skych?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    #username: root
    #password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 30000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j2
    logSlowSql: true
  
  redis:
    timeout:
      seconds: 2
    database: 0
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 4
  
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      fail-on-empty-beans: false
      indent-output: true
    default-property-inclusion: non-null #null不序列化
    deserialization:
      fail-on-unknown-properties: false
    parser:
      allow-unquoted-control-chars: true
      allow-single-quotes: true


mybatis:
  type-aliases-package: com.iotzc.zcms.model
  mapper-locations: classpath:com/iotzc/zcms/dao/*.xml
  
#  config-location: classpath:mybatis-config.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    use-generated-keys: true
    
  
  

---
spring:
  profiles: dev
  
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/czc?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root123
  
  redis:
    host: 127.0.0.1
    port: 6379

  zcms:
    common:
      redis-prefix: CZC_
---
spring:
  profiles: test
  
  zcms:
    common:
      redis-prefix: CZC_
---
spring:
  profiles: prd
  
  zcms:
    common:
      redis-prefix: CZC_
  